generatorName: server-fiber
outputDir: samples/server/petstore/go-fiber-server
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/server-fiber
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
